=== KPatrik22/WYQ5JK_XMLGyak/XMLTaskWYQ5JK/1. feladat/XMLSchemaWYQ5JK.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


	<!-- Elemek, tulajdonságok -->

	<xs:element name="name" type="xs:string" />
	<xs:element name="megallo" type="xs:string" />
	<xs:element name="csuklos" type="xs:boolean" />
	<xs:element name="tipus" type="xs:string" />
	<xs:element name="szuletesi_ido" type="datumType" />
	<xs:element name="eletkor" type="xs:integer" />
	<xs:element name="mikor" type="datumType" />
	<xs:element name="kor" type="xs:integer" />
	<xs:element name="rokoni_kapcsolat" type="xs:string" />

	<xs:attribute name="t_cegjegyzekszam" type="xs:string" />
	<xs:attribute name="mvk_cegjegyzekszam" type="xs:string" />
	<xs:attribute name="sorozatszam" type="xs:integer" />
	<xs:attribute name="szemelyi" type="xs:string" />
	<xs:attribute name="nev" type="xs:string" />


	<!-- Egyszerű típus -->

	<xs:simpleType name="datumType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(19|20)\d\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])"></xs:pattern>
		</xs:restriction>
    	</xs:simpleType>

	<!-- Komplex típusok -->

	<xs:complexType name="teljes_nevType">
        	<xs:sequence>
            		<xs:element name="vezeteknev" type="xs:string" />
            		<xs:element name="keresztnev" type="xs:string" />
        	</xs:sequence>
    	</xs:complexType>	

	<xs:complexType name="megallokType">
		<xs:sequence>
			<xs:element ref="megallo" minOccurs="3" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tulajdonosType">
		<xs:sequence>
			<xs:element ref="name" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute ref="t_cegjegyzekszam" use="required"/>
	</xs:complexType>

	<xs:complexType name="mvkType">
		<xs:sequence>
			<xs:element name="megallok" type="megallokType"/>
		</xs:sequence>
		<xs:attribute ref="mvk_cegjegyzekszam" use="required"/>
		<xs:attribute ref="t_cegjegyzekszam" use="required"/>
	</xs:complexType>

	<xs:complexType name="buszType">
		<xs:sequence>
			<xs:element ref="csuklos"/>
			<xs:element ref="tipus"/>
		</xs:sequence>
		<xs:attribute ref="sorozatszam" use="required"/>
	</xs:complexType>

	<xs:complexType name="soforType">
		<xs:sequence>
			<xs:element ref="szuletesi_ido"/>
			<xs:element name="teljes_nev" type="teljes_nevType" />
			<xs:element ref="eletkor"/>
		</xs:sequence>
		<xs:attribute ref="szemelyi" use="required"/>
	</xs:complexType>

	<xs:complexType name="csaladtagType">
		<xs:sequence>
			<xs:element ref="kor"/>
		</xs:sequence>
		<xs:attribute ref="nev" use="required"/>
	</xs:complexType>

	<!-- Kapcsolótáblák -->

	<xs:complexType name="vezetType">
		<xs:sequence>
            		<xs:element ref="mikor"/>
        	</xs:sequence>
		<xs:attribute name="buszREF" type="xs:integer" use="required"/>
		<xs:attribute name="soforREF" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="rokonType">
		<xs:sequence>
			<xs:element ref="rokoni_kapcsolat"/>
		</xs:sequence>
		<xs:attribute name="soforREF" type="xs:string" use="required"/>
		<xs:attribute name="csaladtagREF" type="xs:string" use="required"/>
	</xs:complexType>



	<xs:element name="WYQ5JK_MVK">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tulajdonos" type="tulajdonosType" maxOccurs="1"/>
				<xs:element name="mvk" type="mvkType" maxOccurs="1"/>
				<xs:element name="busz" type="buszType" minOccurs="3" maxOccurs="unbounded"/>
				<xs:element name="sofor" type="soforType" minOccurs="3" maxOccurs="unbounded"/>
				<xs:element name="vezet" type="vezetType" maxOccurs="unbounded"/>
				<xs:element name="csaladtag" type="csaladtagType" maxOccurs="unbounded"/>
				<xs:element name="rokon" type="rokonType" maxOccurs="unbounded"/>

			</xs:sequence>
		</xs:complexType>

	<!-- Elsődleges kulcsok -->

        <xs:key name="t_cegjegyzekszam">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@t_cegjegyzekszam"/>
        </xs:key>

        <xs:key name="mvk_cegjegyzekszam">
            <xs:selector xpath="mvk"/>
            <xs:field xpath="@mvk_cegjegyzekszam"/>
        </xs:key>

        <xs:key name="sorozatszam">
            <xs:selector xpath="busz"/>
            <xs:field xpath="@sorozatszam"/>
        </xs:key>

        <xs:key name="szemelyi">
            <xs:selector xpath="sofor"/>
            <xs:field xpath="@szemelyi"/>
        </xs:key>

        <xs:key name="nev">
            <xs:selector xpath="csaladtag"/>
            <xs:field xpath="@nev"/>
        </xs:key>
	
	<!-- Idegen kulcsok -->

	<xs:keyref name="buszREF" refer="sorozatszam">
		<xs:selector xpath="busz"></xs:selector>
		<xs:field xpath="@buszREF"></xs:field>
	</xs:keyref>

	<xs:keyref name="soforREF" refer="szemelyi">
		<xs:selector xpath="sofor"></xs:selector>
		<xs:field xpath="@termekREF"></xs:field>
	</xs:keyref>

	<xs:keyref name="csaladtagREF" refer="nev">
		<xs:selector xpath="csaladtag"></xs:selector>
		<xs:field xpath="@termekREF"></xs:field>
	</xs:keyref>

	</xs:element>
</xs:schema>

=== KPatrik22/WYQ5JK_XMLGyak/XMLTaskWYQ5JK/1. feladat/XMLWYQ5JK.xml
<?xml version="1.0" encoding="UTF-8"?>
<WYQ5JK_MVK xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="XMLSchemaWYQ5JK.xsd">

    <!-- Tulajdonos -->

    <tulajdonos t_cegjegyzekszam="05-10-000406">
        <name>Miskolc Holding Önkormányzati Vagyonkezelő Zrt.</name>
    </tulajdonos>

    <!-- MVK -->

    <mvk mvk_cegjegyzekszam="05-10-000147" t_cegjegyzekszam="05-10-000406">
        <megallok>
		<megallo>Egyetemváros</megallo>
        	<megallo>Centrum</megallo>
		<megallo>Búza tér</megallo>
	</megallok>
    </mvk>


    <!-- Busz -->

    <busz sorozatszam="123">
        <csuklos>true</csuklos>
        <tipus>MAN Lion’s City GL A40 CNG</tipus>
    </busz>

    <busz sorozatszam="456">
        <csuklos>false</csuklos>
        <tipus>MAN Lion’s City A21 CNG</tipus>
    </busz>

    <busz sorozatszam="789">
        <csuklos>true</csuklos>
        <tipus>Neoplan N4522 Centroliner</tipus>
    </busz>

    <!-- Sofőr -->

    <sofor szemelyi="000001HE">
        <szuletesi_ido>1965-10-15</szuletesi_ido>
	<teljes_nev>
		<vezeteknev>Kovács</vezeteknev>
		<keresztnev>Béla</keresztnev>
	</teljes_nev>
	<eletkor>58</eletkor>
    </sofor>

    <sofor szemelyi="000002SA">
        <szuletesi_ido>1972-12-04</szuletesi_ido>
	<teljes_nev>
		<vezeteknev>Szabó</vezeteknev>
		<keresztnev>Tamás</keresztnev>
	</teljes_nev>
	<eletkor>51</eletkor>
    </sofor>

    <sofor szemelyi="000003TA">
        <szuletesi_ido>1971-04-29</szuletesi_ido>
	<teljes_nev>
		<vezeteknev>Tóth</vezeteknev>
		<keresztnev>István</keresztnev>
	</teljes_nev>
	<eletkor>52</eletkor>
    </sofor>


    <!-- Vezet -->

    <vezet buszREF="123" soforREF="000002SA">
        <mikor>2023-11-13</mikor>
    </vezet>

    <vezet buszREF="456" soforREF="000003TA">
        <mikor>2023-11-17</mikor>
    </vezet>

    <vezet buszREF="789" soforREF="000001HE">
        <mikor>2023-11-15</mikor>
    </vezet>


    <!-- Családtag -->

    <csaladtag nev="Kovácsné Mária">
        <kor>55</kor>
    </csaladtag>

    <csaladtag nev="Szabó Noémi">
        <kor>7</kor>
    </csaladtag>

    <csaladtag nev="Tóth Géza">
        <kor>12</kor>
    </csaladtag>


    <!-- Rokon -->

    <rokon soforREF="000001HE" csaladtagREF="Kovácsné Mária">
        <rokoni_kapcsolat>házastárs</rokoni_kapcsolat>
    </rokon>

    <rokon soforREF="000002SA" csaladtagREF="Szabó Noémi">
        <rokoni_kapcsolat>gyermek</rokoni_kapcsolat>
    </rokon>

    <rokon soforREF="000003TA" csaladtagREF="Tóth Géza">
        <rokoni_kapcsolat>gyermek</rokoni_kapcsolat>
    </rokon>


</WYQ5JK_MVK>
